2018-08-02 19:57:09,980 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:47]
2018-08-02 19:57:22,184 ERROR: Exception on /reset_password_request [POST] [in /home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/usr/lib/python3.6/smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.6/smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.6/smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/richard/Dev/microblog/app/routes.py", line 164, in reset_password_request
    send_password_reset_email(user)
  File "/home/richard/Dev/microblog/app/email.py", line 22, in send_password_reset_email
    user=user, token=token))
  File "/home/richard/Dev/microblog/app/email.py", line 11, in send_email
    mail.send(msg)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.6/smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.6/smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2018-08-02 20:00:02,776 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:47]
2018-08-02 20:04:21,708 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:47]
2018-08-02 20:04:39,604 ERROR: Exception on /reset_password_request [POST] [in /home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/richard/Dev/microblog/app/routes.py", line 164, in reset_password_request
    send_password_reset_email(user)
  File "/home/richard/Dev/microblog/app/email.py", line 22, in send_password_reset_email
    user=user, token=token))
  File "/home/richard/Dev/microblog/app/email.py", line 11, in send_email
    mail.send(msg)
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/richard/Dev/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/usr/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b63-v6sm873161vkf.26 - gsmtp')
2018-08-02 20:05:13,961 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:47]
2018-08-02 20:46:45,053 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:47]
2018-08-03 09:13:47,117 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:49]
2018-08-03 09:38:26,566 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:51]
2018-08-03 11:35:34,661 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 11:52:01,353 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:00:06,951 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:01:43,112 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:13:56,109 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:19:26,682 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:19:34,448 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:29:53,865 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:30:23,828 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:34:19,475 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:35:46,744 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:35:50,715 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:38:47,154 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:38:56,734 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 12:39:26,575 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 14:30:47,280 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 14:31:08,157 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:54]
2018-08-03 15:06:43,117 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:07:38,012 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:08:08,534 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:08:17,626 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:12:44,910 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:34:21,098 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:34:36,491 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 15:55:27,803 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 16:23:57,046 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 16:25:53,135 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 16:27:52,396 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 16:29:13,130 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:13:06,292 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:34:33,316 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:39:55,329 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:45:26,643 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:49:30,476 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:53:17,548 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:53:25,168 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:54:18,544 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:55:56,236 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
2018-08-03 18:57:39,030 INFO: Microblog startup [in /home/richard/Dev/microblog/app/__init__.py:56]
